version: "3.8"

services:
  app:
    build: .
    container_name: rdmg_app
    restart: unless-stopped
    ports:
      - "80:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=rdmg
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: rdmg_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
